# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CANsetting.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CAN_Setting(object):
    def setupUi(self, CAN_Setting):
        CAN_Setting.setObjectName("CAN_Setting")
        CAN_Setting.resize(613, 214)
        self.widget = QtWidgets.QWidget(CAN_Setting)
        self.widget.setGeometry(QtCore.QRect(31, 31, 571, 160))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_can0 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_can0.setObjectName("lineEdit_can0")
        self.gridLayout_3.addWidget(self.lineEdit_can0, 2, 1, 1, 1)
        self.label_Data = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Data.setFont(font)
        self.label_Data.setObjectName("label_Data")
        self.gridLayout_3.addWidget(self.label_Data, 3, 0, 1, 1)
        self.label_kBaud1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kBaud1.setFont(font)
        self.label_kBaud1.setObjectName("label_kBaud1")
        self.gridLayout_3.addWidget(self.label_kBaud1, 3, 2, 1, 1)
        self.comboBox_CAN0 = QtWidgets.QComboBox(self.widget)
        self.comboBox_CAN0.setObjectName("comboBox_CAN0")
        self.comboBox_CAN0.addItem("")
        self.comboBox_CAN0.addItem("")
        self.comboBox_CAN0.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_CAN0, 1, 1, 1, 1)
        self.lineEdit_can0_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_can0_1.setObjectName("lineEdit_can0_1")
        self.gridLayout_3.addWidget(self.lineEdit_can0_1, 3, 1, 1, 1)
        self.label_kBaud0 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kBaud0.setFont(font)
        self.label_kBaud0.setObjectName("label_kBaud0")
        self.gridLayout_3.addWidget(self.label_kBaud0, 2, 2, 1, 1)
        self.label_Mode = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Mode.setFont(font)
        self.label_Mode.setObjectName("label_Mode")
        self.gridLayout_3.addWidget(self.label_Mode, 1, 0, 1, 1)
        self.checkBox_CAN0 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_CAN0.setFont(font)
        self.checkBox_CAN0.setObjectName("checkBox_CAN0")
        self.gridLayout_3.addWidget(self.checkBox_CAN0, 0, 0, 1, 3)
        self.label_BaudRate0 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_BaudRate0.setFont(font)
        self.label_BaudRate0.setObjectName("label_BaudRate0")
        self.gridLayout_3.addWidget(self.label_BaudRate0, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_kBaud4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kBaud4.setFont(font)
        self.label_kBaud4.setObjectName("label_kBaud4")
        self.gridLayout_2.addWidget(self.label_kBaud4, 3, 2, 1, 1)
        self.lineEdit_CAN1_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_CAN1_2.setObjectName("lineEdit_CAN1_2")
        self.gridLayout_2.addWidget(self.lineEdit_CAN1_2, 3, 1, 1, 1)
        self.label_kBaud3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kBaud3.setFont(font)
        self.label_kBaud3.setObjectName("label_kBaud3")
        self.gridLayout_2.addWidget(self.label_kBaud3, 2, 2, 1, 1)
        self.comboBox_CAN1 = QtWidgets.QComboBox(self.widget)
        self.comboBox_CAN1.setObjectName("comboBox_CAN1")
        self.comboBox_CAN1.addItem("")
        self.comboBox_CAN1.addItem("")
        self.comboBox_CAN1.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_CAN1, 1, 1, 1, 1)
        self.label_Mode1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Mode1.setFont(font)
        self.label_Mode1.setObjectName("label_Mode1")
        self.gridLayout_2.addWidget(self.label_Mode1, 1, 0, 1, 1)
        self.label_BaudRate = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_BaudRate.setFont(font)
        self.label_BaudRate.setObjectName("label_BaudRate")
        self.gridLayout_2.addWidget(self.label_BaudRate, 2, 0, 1, 1)
        self.label_Date1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Date1.setFont(font)
        self.label_Date1.setObjectName("label_Date1")
        self.gridLayout_2.addWidget(self.label_Date1, 3, 0, 1, 1)
        self.lineEdit_CAN1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_CAN1.setObjectName("lineEdit_CAN1")
        self.gridLayout_2.addWidget(self.lineEdit_CAN1, 2, 1, 1, 1)
        self.checkBox_CAN1 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_CAN1.setFont(font)
        self.checkBox_CAN1.setObjectName("checkBox_CAN1")
        self.gridLayout_2.addWidget(self.checkBox_CAN1, 0, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.SAVE = QtWidgets.QPushButton(self.widget)
        self.SAVE.setObjectName("SAVE")
        self.gridLayout.addWidget(self.SAVE, 1, 0, 1, 1)
        self.RESET = QtWidgets.QPushButton(self.widget)
        self.RESET.setObjectName("RESET")
        self.gridLayout.addWidget(self.RESET, 1, 1, 1, 1)

        self.retranslateUi(CAN_Setting)
        QtCore.QMetaObject.connectSlotsByName(CAN_Setting)

    def retranslateUi(self, CAN_Setting):
        _translate = QtCore.QCoreApplication.translate
        CAN_Setting.setWindowTitle(_translate("CAN_Setting", "Form"))
        self.lineEdit_can0.setText(_translate("CAN_Setting", "500"))
        self.label_Data.setText(_translate("CAN_Setting", "Date Rate"))
        self.label_kBaud1.setText(_translate("CAN_Setting", "kBaud"))
        self.comboBox_CAN0.setItemText(0, _translate("CAN_Setting", "CAN"))
        self.comboBox_CAN0.setItemText(1, _translate("CAN_Setting", "ISO CAN FD"))
        self.comboBox_CAN0.setItemText(2, _translate("CAN_Setting", "NON-ISO CAN FD"))
        self.label_kBaud0.setText(_translate("CAN_Setting", "kBaud"))
        self.label_Mode.setText(_translate("CAN_Setting", "Mode"))
        self.checkBox_CAN0.setText(_translate("CAN_Setting", "CAN 0"))
        self.label_BaudRate0.setText(_translate("CAN_Setting", "Baud Rate"))
        self.label_kBaud4.setText(_translate("CAN_Setting", "kBaud"))
        self.label_kBaud3.setText(_translate("CAN_Setting", "kBaud"))
        self.comboBox_CAN1.setItemText(0, _translate("CAN_Setting", "CAN"))
        self.comboBox_CAN1.setItemText(1, _translate("CAN_Setting", "ISO CAN FD"))
        self.comboBox_CAN1.setItemText(2, _translate("CAN_Setting", "NON-ISO CAN FD"))
        self.label_Mode1.setText(_translate("CAN_Setting", "Mode"))
        self.label_BaudRate.setText(_translate("CAN_Setting", "Baud Rate"))
        self.label_Date1.setText(_translate("CAN_Setting", "Date Rate"))
        self.lineEdit_CAN1.setText(_translate("CAN_Setting", "500"))
        self.checkBox_CAN1.setText(_translate("CAN_Setting", "CAN 1"))
        self.SAVE.setText(_translate("CAN_Setting", "SAVE AND OPEN"))
        self.RESET.setText(_translate("CAN_Setting", "RESET"))
